runtime: python27
threadsafe: true

handlers:
- url: /
  script: index.app
- url: /api/station/.*
  script: api.station.app
- url: /static/
  static_dir: views/static

skip_files:
- ^env/.*
- \.git
- .*\.pyc
